/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SecondImport } from './routes/second'
import { Route as FirstImport } from './routes/first'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SecondRoute = SecondImport.update({
  id: '/second',
  path: '/second',
  getParentRoute: () => rootRoute,
} as any)

const FirstRoute = FirstImport.update({
  id: '/first',
  path: '/first',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/first': {
      id: '/first'
      path: '/first'
      fullPath: '/first'
      preLoaderRoute: typeof FirstImport
      parentRoute: typeof rootRoute
    }
    '/second': {
      id: '/second'
      path: '/second'
      fullPath: '/second'
      preLoaderRoute: typeof SecondImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/first': typeof FirstRoute
  '/second': typeof SecondRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/first': typeof FirstRoute
  '/second': typeof SecondRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/first': typeof FirstRoute
  '/second': typeof SecondRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/first' | '/second'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/first' | '/second'
  id: '__root__' | '/' | '/first' | '/second'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirstRoute: typeof FirstRoute
  SecondRoute: typeof SecondRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirstRoute: FirstRoute,
  SecondRoute: SecondRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/first",
        "/second"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/first": {
      "filePath": "first.tsx"
    },
    "/second": {
      "filePath": "second.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
